### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Grynr38** [Salamek/huawei-lte-api#124]
Hi,
I've been using the script for a while I stopped using it in December, I've reactivated my settings today but unable to connect :
```
domass@DomAss:~/domoticz/scripts$` python3 sms.py 33*********** "TESTING "
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8cc26b3550>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.***.***', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8cc26b3550>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/domass/domoticz/scripts/sms.py", line 12, in <module>
    connection = AuthorizedConnection('http://MY_USER:MY_PASSWORD@192.168.***.***/') # If you wish to login on demand (when call requires authorization), pass login_on_demand=True
  File "/home/domass/.local/lib/python3.9/site-packages/huawei_lte_api/AuthorizedConnection.py", line 9, in __init__
    super().__init__(*args, **kwargs)
  File "/home/domass/.local/lib/python3.9/site-packages/huawei_lte_api/Connection.py", line 27, in __init__
    super().__init__(url, timeout=timeout, requests_session=requests_session)
  File "/home/domass/.local/lib/python3.9/site-packages/huawei_lte_api/Session.py", line 69, in __init__
    self._initialize_csrf_tokens_and_session()
  File "/home/domass/.local/lib/python3.9/site-packages/huawei_lte_api/Session.py", line 146, in _initialize_csrf_tokens_and_session
    response = self.requests_session.get(self.url, timeout=self.timeout)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.***.***', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8cc26b3550>: Failed to establish a new connection: [Errno 110] Connection timed out'))
domass@DomAss:~/domoticz/scripts$ ping 192.168.***.***
PING 192.168.***.*** (192.168.***.***) 56(84) bytes of data.
64 bytes from 192.168.***.***: icmp_seq=1 ttl=63 time=1.12 ms
64 bytes from 192.168.***.***: icmp_seq=2 ttl=63 time=0.701 ms
```
LAN ip is correct, user:pass is correct, ping does reply

**Comment by Salamek** [comment]
```
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
```

Well, library is unable to connect to your modem at port 80 at lowest level (socks) and there is nothing that I can do about it, make sure that:

* IP address is correct
* Router web UI is listening on port 80 (there may be automatic router firmware update moving it to 443, if that is the case you need to use https:// and disable SSL cert checking, see https://github.com/Salamek/huawei-lte-api/blob/master/examples/ignore_ssl_check.py)
* There are no firewall rules preventing connection
