### ISSUE TITLE
could you add the restart precedure on the code ???

### ISSUE THREAD

**Issue by drepou** [Salamek/huawei-lte-api#138]
I looked to api but dint find the possibility to restart the router from webui api. because B715 have on issue on single 4G band with free the connection is freezed every 12h and nothing else than reboot solve the issue ( it a FAI issue ! )

Can you  please add that add the reboot possibility to the lib ???

I tryed this project https://github.com/mkorz/b618reboot
 to do it but i get an error with salt parsing and encoding i have no idea how to solve it 

i get this error running reboot_router.py with py version 3.7.3

Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux

Traceback (most recent call last):
File "./reboot_router.py", line 133, in
sys.exit(main())
File "./reboot_router.py", line 129, in main
reboot(client, ROUTER, USER, PASSWORD)
File "./reboot_router.py", line 109, in reboot
verification_token = login(client, server, user, password)
File "./reboot_router.py", line 92, in login
clientnonce, servernonce, password, salt, iterations).decode('UTF-8')
File "./reboot_router.py", line 44, in get_client_proof
'sha256', password, bytearray.fromhex(salt), iterations)
TypeError: a bytes-like object is required, not 'str'

can you help me ??? it seem that bytearray.fromhex(salt) cause the issue i get strange value
i get this from resquest : 05b956492ed7fa6d9fac08b2a8ea.... ( i give you only partial value for security raison ) and then convert i get :
bytearray(b'\x05\xb9VI.\xd7\xfam\x9f\xac\x08\xb2\xa8\xea\x91;[i\xff\xfb\x80\xdfuS\ ..... for me this not valid hex ???

**Comment by drepou** [comment]
> @drepou just reboot the router using this library by calling `device.set_control(ControlModeEnum.REBOOT)`

hooo thanks
