### ISSUE TITLE
Can't connect to my modem

### ISSUE THREAD

**Issue by Emilianocm23** [Salamek/huawei-lte-api#186]
hello, i get an error when trying to connect use your library

My code:

```
from huawei_lte_api.Client import Client
from huawei_lte_api.Connection import Connection


with Connection('http://admin:admin@192.168.9.1/') as connection:
    client = Client(connection)
    print(client.device.signal())
    # print(client.device.information())

```

Exception:
```
Traceback (most recent call last):
  File "C:\Users\pc\PycharmProjects\project\venv\Lib\site-packages\huawei_lte_api\api\User.py", line 61, in _login
    result = self._session.post_set('user/login', {
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\PycharmProjects\project\venv\Lib\site-packages\huawei_lte_api\Session.py", line 215, in post_set
    self._post(endpoint, data, refresh_csrf, prefix, is_encrypted, is_json)
  File "C:\Users\pc\PycharmProjects\project\venv\Lib\site-packages\huawei_lte_api\Session.py", line 34, in wrapped
    return fn(*args, **kw)
           ^^^^^^^^^^^^^^^
  File "C:\Users\pc\PycharmProjects\project\venv\Lib\site-packages\huawei_lte_api\Session.py", line 254, in _post
    response_data = cast(str, self._check_response_status(self._process_response_data(response)))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\PycharmProjects\project\venv\Lib\site-packages\huawei_lte_api\Session.py", line 156, in _check_response_status
    raise error_code_to_exception.get(error_code, ResponseErrorException)(
huawei_lte_api.exceptions.ResponseErrorException: 100006: Unknown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pc\PycharmProjects\project\4g\reload.py", line 5, in <module>
    with Connection('http://admin:admin@192.168.13.1/') as connection:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\PycharmProjects\project\venv\Lib\site-packages\huawei_lte_api\Connection.py", line 34, in __init__
    self.user_session = UserSession(
                        ^^^^^^^^^^^^
  File "C:\Users\pc\PycharmProjects\project\venv\Lib\site-packages\huawei_lte_api\api\User.py", line 27, in __init__
    self.user.login(username, password, True)
  File "C:\Users\pc\PycharmProjects\project\venv\Lib\site-packages\huawei_lte_api\api\User.py", line 112, in login
    return self._login(username, password, PasswordTypeEnum(int(state_login.get('password_type', 0))))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\PycharmProjects\project\venv\Lib\site-packages\huawei_lte_api\api\User.py", line 86, in _login
    raise error_code_to_exception.get(e.code, ResponseErrorException)(
huawei_lte_api.exceptions.ResponseErrorException: 100006: Unknown
```

**Comment by Salamek** [comment]
@Emilianocm23 i have my E3372 working right here, but it does not use login or password in URI (i did not set any)

```python
from huawei_lte_api.Client import Client
from huawei_lte_api.Connection import Connection
with Connection('http://192.168.8.1/') as connection:
    client = Client(connection) 
    print(client.monitoring.status())
```


also in your backtrace i see `http://admin:admin@192.168.13.1/` correct address on your network looks like 192.168.9.1

And BTW from folder names in your path (4g\reload.py)... are you trying to invent the wheel? :-) https://github.com/Salamek/netkeeper

**Comment by Emilianocm23** [comment]
> 

Thanks for your fast reply @Salamek 

I used the code you sent me and it's now working. Sorry i have multiple modems connected at the same time on a different ip segment. 

Im doing a script to basically disconnect and connect the modems from network to get a new IP address.

```
client.dial_up.set_mobile_dataswitch(0)
client.dial_up.set_mobile_dataswitch(1)
```

Running those commands will basically do what i need right?

**Comment by Salamek** [comment]
This seems to be solved
