### ISSUE TITLE
Unable to connect to Huawei B535-333 with the error 125003 (Wrong token)

### ISSUE THREAD

**Issue by Wildside-UK** [Salamek/huawei-lte-api#187]
Traceback (most recent call last):
  File "C:\Users\steve\AppData\Local\Programs\Python\Python311\Lib\site-packages\huawei_lte_api\api\User.py", line 61, in _login
    result = self._session.post_set('user/login', {
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steve\AppData\Local\Programs\Python\Python311\Lib\site-packages\huawei_lte_api\Session.py", line 215, in post_set
    self._post(endpoint, data, refresh_csrf, prefix, is_encrypted, is_json)
  File "C:\Users\steve\AppData\Local\Programs\Python\Python311\Lib\site-packages\huawei_lte_api\Session.py", line 34, in wrapped
    return fn(*args, **kw)
           ^^^^^^^^^^^^^^^
  File "C:\Users\steve\AppData\Local\Programs\Python\Python311\Lib\site-packages\huawei_lte_api\Session.py", line 254, in _post
    response_data = cast(str, self._check_response_status(self._process_response_data(response)))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steve\AppData\Local\Programs\Python\Python311\Lib\site-packages\huawei_lte_api\Session.py", line 156, in _check_response_status
    raise error_code_to_exception.get(error_code, ResponseErrorException)(
huawei_lte_api.exceptions.ResponseErrorWrongSessionToken: 125003: Wrong Session Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\steve\Documents\GitHub\api\main.py", line 5, in <module>
    with Connection('http://admin:53jAqHGfqrqD@192.168.8.1/') as connection:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steve\AppData\Local\Programs\Python\Python311\Lib\site-packages\huawei_lte_api\Connection.py", line 34, in __init__
    self.user_session = UserSession(
                        ^^^^^^^^^^^^
  File "C:\Users\steve\AppData\Local\Programs\Python\Python311\Lib\site-packages\huawei_lte_api\api\User.py", line 27, in __init__
    self.user.login(username, password, True)
  File "C:\Users\steve\AppData\Local\Programs\Python\Python311\Lib\site-packages\huawei_lte_api\api\User.py", line 112, in login
    return self._login(username, password, PasswordTypeEnum(int(state_login.get('password_type', 0))))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steve\AppData\Local\Programs\Python\Python311\Lib\site-packages\huawei_lte_api\api\User.py", line 86, in _login
    raise error_code_to_exception.get(e.code, ResponseErrorException)(
huawei_lte_api.exceptions.ResponseErrorException: 125003: Unknown

**Comment by joshuadouch** [comment]
I'm also still experiencing this issue
