### ISSUE TITLE
Error: 113004

### ISSUE THREAD

**Issue by chava2708** [Salamek/huawei-lte-api#197]
When I tried to send 4 messages one after the other, it displayed that error 

[2023-10-20 03:16:41,774] ERROR in app: Exception on /mandarMensaje [POST]
Traceback (most recent call last):
  File "/root/Documentos/python/sms_api/sms-api-env/lib64/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/Documentos/python/sms_api/sms-api-env/lib64/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/Documentos/python/sms_api/sms-api-env/lib64/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/Documentos/python/sms_api/sms-api-env/lib64/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/Documentos/python/sms_api/api_sms.py", line 19, in mandarMensaje
    return jsonify(men.mandaMensaje(mensaje))
  File "/root/Documentos/python/sms_api/mensaje.py", line 17, in mandaMensaje
    if client.sms.send_sms([self.numero], mensaje) == ResponseEnum.OK.value:
  File "/root/Documentos/python/sms_api/sms-api-env/lib64/python3.6/site-packages/huawei_lte_api/api/Sms.py", line 175, in send_sms
    ('Date', Tools.datetime_to_string(from_date))
  File "/root/Documentos/python/sms_api/sms-api-env/lib64/python3.6/site-packages/huawei_lte_api/Session.py", line 215, in post_set
    self._post(endpoint, data, refresh_csrf, prefix, is_encrypted, is_json)
  File "/root/Documentos/python/sms_api/sms-api-env/lib64/python3.6/site-packages/huawei_lte_api/Session.py", line 34, in wrapped
    return fn(*args, **kw)
  File "/root/Documentos/python/sms_api/sms-api-env/lib64/python3.6/site-packages/huawei_lte_api/Session.py", line 254, in _post
    response_data = cast(str, self._check_response_status(self._process_response_data(response)))
  File "/root/Documentos/python/sms_api/sms-api-env/lib64/python3.6/site-packages/huawei_lte_api/Session.py", line 158, in _check_response_status
    error_code
huawei_lte_api.exceptions.ResponseErrorException: 113004: Unknown

**Comment by Salamek** [comment]
Maybe some kinda of rate limiting?
