### ISSUE TITLE
Support for self-signed/invalid certificates

### ISSUE THREAD

**Issue by rradar** [Salamek/huawei-lte-api#31]
Hello!

I'm having the problem that my huawei firmware comes with a weird self-signed/invalid certificate

> ![image](https://user-images.githubusercontent.com/34582688/57380053-0ab74600-71a0-11e9-8e89-f20ed65225f7.png)

which stops me from using the huawei-lte-api.

I get this error using the huawei-lte-monitoring script from @littlejo 

```
Traceback (most recent call last):
  File "/home/userunkown/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/userunkown/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/userunkown/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/userunkown/.local/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/userunkown/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 358, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/userunkown/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/userunkown/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/userunkown/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.1.1', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "display_traffic_signal.py", line 42, in <module>
    main()
  File "display_traffic_signal.py", line 30, in main
    connection = AuthorizedConnection(f'http://{ip}/', login, password)
  File "/home/userunkown/.local/lib/python3.6/site-packages/huawei_lte_api/AuthorizedConnection.py", line 29, in __init__
    super(AuthorizedConnection, self).__init__(url)
  File "/home/userunkown/.local/lib/python3.6/site-packages/huawei_lte_api/Connection.py", line 24, in __init__
    self._initialize_csfr_tokens_and_session()
  File "/home/userunkown/.local/lib/python3.6/site-packages/huawei_lte_api/Connection.py", line 73, in _initialize_csfr_tokens_and_session
    response = requests.get(self.url)
  File "/home/userunkown/.local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/userunkown/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/userunkown/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/userunkown/.local/lib/python3.6/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/userunkown/.local/lib/python3.6/site-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/userunkown/.local/lib/python3.6/site-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/home/userunkown/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/userunkown/.local/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.1.1', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
```

**Comment by Salamek** [comment]
@rradar Can you pls check against branch https://github.com/Salamek/huawei-lte-api/tree/issue-31 and let me know if it works ok ?

In this branch you can set verify_ssl=False as connection parameter:

```python
AuthorizedConnection(f'http://{ip}/', login, password, verify_ssl=False)
```

BTW: This approach is not recommended way how to hanlde self signed/unknow certificates, you should import that certificate to machine where you are using this library and make it trusted...

**Comment by rradar** [comment]
@Salamek thank's for your exclusive branch for me! I'm suffering right now using it. I installed the main version with pip3 (*buntu based distro) and have actually no idea how to get this one here manually compiled. I did clone this tree but would need some short instruction how to go further! Thank's :wink:

**Comment by Salamek** [comment]
@rradar 

1. Clone this repository:
```
git clone  git@github.com:Salamek/huawei-lte-api.git
```
2. cd into it:
```sh
cd huawei-lte-api
```

3. Switch to `issue-31` branch
```sh
git checkout issue-31
```

4. Create file `test.py` with this content inside cloned huawei-lte-api:
```python
from huawei_lte_api.Client import Client
from huawei_lte_api.AuthorizedConnection import AuthorizedConnection

connection = AuthorizedConnection('http://admin:MY_SUPER_TRUPER_PASSWORD@192.168.8.1/', verify_ssl=False)

client = Client(connection)
print(client.device.information()) 

```

5. Test it!
```sh
python3 test.py
```

It should use cloned `huawei-lte-api` instead of pip3 installed one (if you want to be sure, just uninstall pip installed huawei-lte-api) and print out device info... Let me know how it works so i can release new pip version or fix what is broken...

**Comment by rradar** [comment]
@Salamek 

I tried with a different command as with `git clone git@github.com:Salamek/huawei-lte-api.git` I always get `Permission denied (publickey)` errors (need to fix this later)

> `git clone https://github.com/Salamek/huawei-lte-api
> `Cloning into 'huawei-lte-api'...
> cremote: Enumerating objects: 32, done.
> remote: Counting objects: 100% (32/32), done.
> remote: Compressing objects: 100% (25/25), done.
> remote: Total 680 (delta 12), reused 15 (delta 5), pack-reused 648
> Receiving objects: 100% (680/680), 109.98 KiB | 120.00 KiB/s, done.
> Resolving deltas: 100% (414/414), done.

..entering the new folder...

> `git checkout issue-31`
> Branch 'issue-31' set up to track remote branch 'issue-31' from 'origin'.
> Switched to a new branch 'issue-31'

...creating the test.py and running it:

>  `python test.py`
> ```
>  Traceback (most recent call last):
>    File "test.py", line 1, in <module>
>      from huawei_lte_api.Client import Client
>    File "/home/user/Apps/huawei-lte-api/huawei_lte_api/Client.py", line 39
>      def __init__(self, connection: Connection):
>                                   ^
>  SyntaxError: invalid syntax
> ```

I'm not sure if their was a problem choosing the right branch? Any idea?

**Comment by Salamek** [comment]
@rradar you must use python3!
```sh
python3 test. py
```

**Comment by rradar** [comment]
thank's @Salamek this makes sense :wink: 

Here is my output:

`python3 test.py 
`
```
/home/user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/home/user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    connection = AuthorizedConnection('http://admin:passwd123!@192.168.1.1/', verify_ssl=False)
  File "/home/user/Apps/huawei-lte-api/huawei_lte_api/AuthorizedConnection.py", line 29, in __init__
    super(AuthorizedConnection, self).__init__(url, verify_ssl=verify_ssl)
  File "/home/user/Apps/huawei-lte-api/huawei_lte_api/Connection.py", line 37, in __init__
    self._initialize_csfr_tokens_and_session()
  File "/home/user/Apps/huawei-lte-api/huawei_lte_api/Connection.py", line 93, in _initialize_csfr_tokens_and_session
    self.request_verification_tokens.append(self._get_token())
  File "/home/user/Apps/huawei-lte-api/huawei_lte_api/Connection.py", line 153, in _get_token
    data = self.get('webserver/token')
  File "/home/user/Apps/huawei-lte-api/huawei_lte_api/Connection.py", line 18, in wrapped
    return fn(*args, **kw)
  File "/home/user/Apps/huawei-lte-api/huawei_lte_api/Connection.py", line 150, in get
    return self._check_response_status(self._process_response_xml(response.content))
  File "/home/user/Apps/huawei-lte-api/huawei_lte_api/Connection.py", line 50, in _process_response_xml
    return xmltodict.parse(xml, dict_constructor=dict)
  File "/home/user/.local/lib/python3.6/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: mismatched tag: line 11, column 2

```

**Comment by Salamek** [comment]
@rradar that looks like different issue, it fails to parse XML response from router...

can you run:

```
curl http://192.168.1.1 -o index.html
curl http://192.168.1.1/webserver/token -o out.xml
```

And post content of `index.html` `out.xml` here ?

**Comment by rradar** [comment]
@Salamek 

now we are getting closer... both have the same "content" a 302 error exactly

```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>

  <head>
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8">
    <title>302 Moved Temporarily</title>
  </head>

  <body bgcolor="#cc9999" text="#000000" link="#2020ff" vlink="#4040cc">

    <h4>302 Moved Temporarily</h4>
Redirect.
    <hr>

    <address><a href="http://www.acme.com/software/mini_httpd/">mini_httpd</a></address>

  </body>

</html>
```

I guess the device I'm trying to use is not (yet?) supported. I searched some of the supported models and found quite similar screenshots of the web interface so I thought it might be supported. I try to get your script running on a huawei b2368-22 (https://www.vodafone.cz/pece/osobni-a-firemni/otazky/pevny-internet/modem-b2368-22/). If there is something I can help with getting this thing supported I would be happy to contribute!

**Comment by Salamek** [comment]
@rradar try to use https:// instead of http when testing Connection... this may be just redirect from http to https...

**Comment by rradar** [comment]
@Salamek 
curl gives me this error: `curl: (60) SSL certificate problem: self signed certificate`

When I open the links with a browser I get `**404**` for `https://192.168.1.1/webserver/token` and a force redirect to `**https://192.168.1.1/login.cgi**` when entering `https://192.168.1.1/index.html`

**Comment by Salamek** [comment]
@rradar try to use https:// in AuthorizedConnection() call in test.py file pls...
and could you get `https://192.168.1.1/login.cgi` page HTML code for me ?

**Comment by rradar** [comment]
@Salamek I get the same error using https in test.py...

Here is the login.cgi code:


```html

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<META HTTP-EQUIV="Cache-Control" CONTENT="no-cache,no-store">
<META HTTP-EQUIV="X-Xss-Protection" CONTENT="'1; mode=block'">
<META HTTP-EQUIV="X-Content-Type-Options" CONTENT="nosniff">
<META HTTP-EQUIV="Content-Security-Policy" CONTENT="default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline' ">
<link href="css/reset.css" rel="stylesheet" type="text/css" />
<link href="css/brick.css" rel="stylesheet" type="text/css" />
<title>.:: B2368-22 ::.</title>







<script src="js/jquery-1.3.2.min.js" type="text/javascript"></script>
<script src="js/jquery.validate.pack.js" type="text/javascript"></script>
<script src="js/jquery.base64.js" type="text/javascript"></script>
<script type="text/javascript">


window.onload=function(){
     
        try{
			CheckCssDown();
			CheckBgPicDown();
			CheckjQueryDown();
		}
		catch(e)
		{
			alert("css error");
		}
		
    };

    function CheckjQueryDown()
    {
    	if (typeof jQuery == 'undefined' ) {
    	
    	   console.log("load jquery failed");
		   window.location.reload(true);
		}

		try{
		    var temp;
			$.base64.encode(temp);
			$("#login").validate({
			});
		
		}
		catch(e)
		{
		  console.log("base64 or validate js file failed");
		  window.location.reload(true);
		}
    }

    function CheckCssDown()
    {
	    var links=document.getElementsByTagName("link");

	    for(i=0;i<links.length;i++) 
		{
			CheckSourceFileDown(links[i]);
		}	
    }
    
	function CheckSourceFileDown(link)
	{   
	
		var rules=link.sheet.cssRules||link.sheet.rules||document.styleSheets;

		if(rules.length == 0)
		{
			window.location.reload(true);
		}
	}

	function CheckBgPicDown()
	{

		try{
			var bg = new Image();
			bg.src = "../images/bg.jpg";
			
			if(bg.width == 0)
			{
				window.location.reload(true);
			}
		}
		catch(e)
		{
			console.log(error);
		}

	}
	
function chkPasswdComplexityExp1(passwd){
    var re = /^[!-~]*[a-zA-Z0-9]+[!-~]*$/;

    if( re.test( passwd ) )
    {
		return true;
    }
    else
    {
		return false;
    }
}

function chkPasswdComplexityExp2(passwd){
    var re = /[a-zA-Z0-9]*$/;

    if( re.test( passwd ) )
    {
		return true;
    }
    else
    {
		return false;
    }
}

function chkPasswdComplexityAdvance(passwd){
    var counter = 0;
    
    if(isUpper(passwd) == true)
        counter++;
    if(islower(passwd) == true)
		counter++;
    if(isdigit(passwd) == true)
        counter++;
    if(isSpecialCharacter(passwd) == true)
        counter++;
        
    if(counter > 2)
        return true;
    else
        return false;
}

function isUpper(input){
    var re = /[A-Z]+/;

    if( re.test( input ) )
    {
		return true;
    }
    else
    {
		return false;
    }
}

function islower(input){
    var re = /[a-z]+/;

    if( re.test( input ) )
    {
		return true;
    }
    else
    {
		return false;
    }
}

function isdigit(input){
    var re = /[0-9]+/;

    if( re.test( input ) )
    {
		return true;
    }
    else
    {
		return false;
    }
}

function isSpecialCharacter(input){
    var re = /[!\"#$%&\'()*+,-.\/:;<=>?@\[\\\]\^_`{|}~]+/;

    if( re.test( input ) )
    {
		return true;
    }
    else
    {
		return false;
    }
}
var ns, ie;

if(navigator.appName == "Netscape") {
	ns = true; ie = false;
} else if(navigator.appName == "Microsoft Internet Explorer") {
	ie = true; ns = false;
} else {
	ns = false; ie = false;
}

function chkChar(event) {
	if(ns)
		val = event.which;
	else
		val = event.keyCode;
	if(val == 0 || val == 8)
		return true;

	if((val > 47 && val < 58) || (val > 64 && val < 91) || (val > 96 && val < 123) || (val == 45) || (val == 46) || (val == 64) || (val == 95))
		return true;
	else
		return false;
}

$(function(){
function showTroubleShooting(src){ var content = '<iframe frameborder=0 src="' + src + '" style=" width:100%; height:360px; ">'
                $.modal(content, {
                    escClose: false, 
                    opacity: 85,
                    position: ['140px'],
                    containerCss: {
                    backgroundImage:"url(/images/bg.gif)",
                        //backgroundColor:"#fff",
                        height: 360,
                        padding: 0,
                        width: 700
                    }
                });
                }
              if (window.location.search.substring(1) == 'th=1') 
                   showTroubleShooting("troubleshooting.html");
         
              if (window.location.search.substring(1) == 'th=5') 
                   showTroubleShooting("message.html");

            });
</script>
<script type="text/javascript">
function PrintDateAndTime()
{
	var min = document.getElementById("mtenCurrent_Min").value;
	var sec = document.getElementById("mtenCurrent_Sec").value;

	if ( min > 0 ) {
		if ( sec > 0 ) {
			document.getElementById("showTime").innerHTML = min + "Min "
					+ sec + "Sec";
		}
		else {
			document.getElementById("showTime").innerHTML = min + "Min";
		}
	}
	else {
		if ( sec > 0 ) {
			document.getElementById("showTime").innerHTML = sec + "Sec";
		}
		else {
			document.getElementById("showTime").innerHTML = "";
		}
	}

}

function Changedisabled()
{
	var min = document.getElementById("mtenCurrent_Min").value;
	var sec = document.getElementById("mtenCurrent_Sec").value;

	if ( min != 0 ||  sec != 0) {
		document.getElementById("username").disabled = "disabled";
    	document.getElementById("userpassword").disabled = "disabled";
    	}
    else{
		document.getElementById("username").disabled = "";
    	document.getElementById("userpassword").disabled = "";
    }
}

function DecreaseSec()
{
	var Min=0, Sec=0;

	Sec = parseInt(document.getElementById("mtenCurrent_Sec").value, 10);
	if ( Sec > 0 )
	{
		document.getElementById("mtenCurrent_Sec").value = Sec;
		PrintDateAndTime();
		Sec = Sec - 1;
		document.getElementById("mtenCurrent_Sec").value = Sec;
		setTimeout('DecreaseSec()', 1000);
		return;
	}

	Min = parseInt(document.getElementById("mtenCurrent_Min").value, 10);
	
	if ( Min > 0 )
	{
		document.getElementById("mtenCurrent_Min").value = Min;
		PrintDateAndTime();
		Min = Min - 1;
		document.getElementById("mtenCurrent_Min").value = Min;
		document.getElementById("mtenCurrent_Sec").value = 59;
		setTimeout('DecreaseSec()', 1000);
		return;
	}
	PrintDateAndTime();
	window.parent.location.href='/login.cgi';
	return;
}

function getExplorerInfo() 
{
    var explorer = window.navigator.userAgent.toLowerCase();
    
	if (explorer.indexOf("edge:") >= 0) {
        var ver = explorer.match(/edge\/([\d.]+)/)[1];
        return { type: "edge", version: ver , explorerInfo:explorer};
    }
	//ie 11 
	if (explorer.indexOf("rv:") >= 0 && explorer.indexOf(") like gecko") >= 0) {
        var ver = explorer.match(/rv:([\d.]+)\) like gecko/)[1];
        return { type: "IE", version: ver , explorerInfo:explorer};
    }
	//ie 10 ~ older 
    if (explorer.indexOf("msie") >= 0) {
        var ver = explorer.match(/msie ([\d.]+)/)[1];
        return { type: "IE", version: ver , explorerInfo:explorer};
    }

    //firefox 
    if (explorer.indexOf("firefox") >= 0) {
        var ver = explorer.match(/firefox\/([\d.]+)/)[1];
        return { type: "firefox", version:ver , explorerInfo:explorer};
    }

    //Chrome
    if (explorer.indexOf("chrome") >= 0) {
        var ver = explorer.match(/chrome\/([\d.]+)/)[1];
        return { type: "chrome", version: ver, explorerInfo:explorer };
    }

    //Opera
    if (explorer.indexOf("opera") >= 0) {
        var ver = explorer.match(/opera.([\d.]+)/)[1];
        return { type: "opera", version: ver, explorerInfo:explorer };
    }

    //Safari
    if (explorer.indexOf("safari") >= 0) {
        var ver = explorer.match(/version\/([\d.]+)/)[1];
        return { type: "safari", version: ver, explorerInfo:explorer};
    }
	
    return { type: "other", version: "0", explorerInfo:explorer };
}

function cmpVer(strCurr, strDefault)
{
	try {
		if (parseInt(strCurr[0]) >  parseInt(strDefault[0]))
		{
			return true;
		}
		else if (parseInt(strCurr[0]) ==  parseInt(strDefault[0]))
		{
			if (parseInt(strCurr[1]) >=  parseInt(strDefault[1]))
			{
				return true;
			}
			else
			{
				return false;
			}
		}
		else
		{
			return false;
		}
	}
	catch(err)
	{
		return false;
	}
	
	return false;
}

var verIE =      new Array("11"      , "0");
var verChrome =  new Array("49"  , "0");
var verFireFox = new Array("45" , "0");
var verSafari =  new Array("10"  , "1");


function chkBrowserVerVaild()
{
	var explorerInfo = getExplorerInfo();
	var type = explorerInfo.type;
	var version = explorerInfo.version;
	var acVer = version.split('.');
	
	if (type.indexOf("edge") >= 0) 
	{
		return true;
	}
	else if (type.indexOf("IE") >= 0) 
	{
		return cmpVer(acVer, verIE);
	}
	else if (type.indexOf("chrome") >= 0) 
	{
		return cmpVer(acVer, verChrome);
	}
	else if (type.indexOf("firefox") >= 0) 
	{
		return cmpVer(acVer, verFireFox);
	}
	else if (type.indexOf("safari") >= 0) 
	{
		return cmpVer(acVer, verSafari);
	}
	else
	{
		return false;
	}

	return false;
}

function showBrowserVerInfo()
{
	var chkValid = chkBrowserVerVaild();
	if (chkValid != true)
	{
		$("#BrowserVer").html("Your browser is not compatible.");
		$("#BrowserSuggest").html("Recommend to use" 
						 		+ " IE " + verIE[0] + '.' + verIE[1] 
								+ ", chrome "  + verChrome[0]  + '.' + verChrome[1] 
								+ ", firefox " + verFireFox[0] + '.' + verFireFox[1] 
								+ ", safari "  + verSafari[0]  + '.' + verSafari[1] 
								+ " or later version browsers.");
		$("#BrowserChk").css('display','block'); 
		
	}
}

$( document ).ready(function() {
		var status = '0';

		if(status != '0'){
			if (status == '2'){
				$("#loginErrorMessage").html("Please wait for ");
				DecreaseSec();
			}
			else
				$("#loginErrorMessage").html("<font color='#DD0000'></font>");
				
			Changedisabled();
		}


		$("#login").validate({
		});
		
		showBrowserVerInfo();
		
});

document.onkeyup = function (e) 
{
    var ev = e || window.event;
	var code = ev.charCode || ev.keyCode; 
    if (code == 13) 
	{
		ButtonClick(1);
    }  
}  

function validform(){	return $("#login").validate({});}

function ButtonClick(value)
{

	var passwd = document.forms[0].password.value;
	var username = document.forms[0].UserName.value;
	
	validform().form();
	
	var encode_submit_value = "";
	if (passwd != "" && username != "")
	{
		var encode_submit_value = $.base64.encode(passwd);
		document.forms[0].password.value = "";
		document.forms[0].hiddenPassword.value = encode_submit_value;
		document.forms[0].submitValue.value = value;
		document.forms[0].submit();
	}

	return;
}


function MultilingualAPI(){
	document.getElementById("languageChange").value=1;
	document.forms[0].submit(); 
}


</script>







</head>
<body class="loginbg">
<div class="logo"></div>

<div class="wraplogin">
	<div class="header_position"><div class="logoWb"></div></div>
	<div class="logincenter"><div class="login_left_pic"></div>
		<div class="login_right">
			<div>
				<ul>
				<span class="title_index">Welcome</span><br />
				  <li class="content_word">Welcome to B2368-22 configuration interface. Please enter username and password to login.<br></li>
				  <li class="content_word" id="BrowserChk" name="BrowserChk" style="display:none;">
					<div><b class="r1"></b><b class="r2"></b><b class="r3"></b><b class="r4"></b><b class="r4"></b></div>
					<div>
						<span id="BrowserVer" name="BrowserVer"></span></br>
						<span id="BrowserSuggest" name="BrowserSuggest"></span>
					</div>
					<div><b class="r4"></b><b class="r4"></b><b class="r3"></b><b class="r2"></b><b class="r1"></b></div>
				  </li>
				    <div><font size='2' color='#DD0000'><label class="content_word">  </label></font></div>
				  	<div><font size='2' color='#DD0000'><label id="loginErrorMessage"></label><label id="showTime"></label><span></span></font></div>
				    <div>
					  	<form action="login.cgi" method="post" id="login">

						<input type="hidden" id="authToken" name="authToken" value="+yqEEuq0HMuNEubFTF8CFGs5m5Bxa7nGb5zpjBHS5L+b+M0Ij48IDcwlC8JiSRta"/>
						<fieldset><ul>
						    <input type="HIDDEN" name="mtenCurrent_Min" id="mtenCurrent_Min" size="2" maxlength="2" value="" >
						    <input type="HIDDEN" name="mtenCurrent_Sec" id="mtenCurrent_Sec" size="2" maxlength="2" value="" >
						    <input type="HIDDEN" name="accountLock" id="accountLock" size="2" maxlength="2" value="" >

						<li style=" margin-top:10px;">
							<span><label for="language" style="width: 100px;" class="content_word_title"><span class="required">Language:</span></label></span>
						</li>
						<li>
							<input type="hidden" name="languageChange" id="languageChange" value="0">
							<input type="hidden" name="languageSelected" id="languageSelected" value="ENG">
							<span style="position:absolute; left:120px;"><select name="Multilingual" id="Multilingual" onChange="MultilingualAPI();">
<!-- Important!! If add a new language, also need to add this language to FWUpTooLarge.html -->

								<option value="0" selected="selected">English</option>

		





                				<option value="1" >Espa&#241;ol</option>


								<option value="2" >&#268;e&#353;tina</option>




							</select></span>
						</li>
						<br />

								<li style=" margin-top:10px;">
									<span><label for="username" style="width: 100px;" class="content_word_title"><span class="required">Username:</span></label></span>
									<span style="position:absolute; left:120px;"><input name="UserName" type="text" class="text required" id="username" value="" size="20" maxlength="30" autocomplete="off" onKeyPress="return chkChar(event);" /></span>
									<span style="position:absolute;  margin-left:170px;">
										<label for="username" class="error">Username is required.</label>
									</span>
								</li>
								
								<br />
								<li style=" margin-top:10px; clear:both;">
									<span><label for="userpassword" style="width: 100px;" class="content_word_title"><span class="required">Password:</span></label></span>
									<span style="position:absolute; left:120px;"><input name="password" type="password" class="text required" id="userpassword" size="20" maxlength="512" value="" autocomplete="off" /></span>
									<span style="position:absolute; left:120px; margin-top:20px;">  </span>
									<input type="hidden" name="hiddenPassword" size="30" maxlength="256">
									<span style="position:absolute; margin-left:170px;">
										<label for="userpassword" class="error">Password is required.</label>
									</span>
								</li>
								
								<li class="login_button">
								  <input type="button" value="Login" onClick="ButtonClick(1)" />
								  <input type="hidden" name="submitValue">
								</li>
							</ul>
							</fieldset>
						  </form>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>

</div>
</body>
</html>
```

**Comment by Salamek** [comment]
@rradar hmm... i have bad news for you, this admin interface looks completely different than this library is expecting. (different endpoint names, MPA...) It looks like they changed their firmware supplier for the worst (older MPA solution)...

I cant create support for this device till i have it in my hands... sorry.

**Comment by rradar** [comment]
Thank's @Salamek for the investigations! Maybe it will become interesting again at some point. The same hardware exists also with a 5g modem instead of the 4g one...

Let's see what the future brings ;)
