### ISSUE TITLE
*Testing Hardware needed*

### ISSUE THREAD

**Issue by Salamek** [Salamek/huawei-lte-api#50]
# Why ?

**Testing HW** is **needed** to properly maintain this library and to solve some issues:
#4 I need real HW to write full coverage unittests (i will ~use dumped responses in tests)
#1 I need real HW to write full documentation
#2 I need real HW to test this functionality and add some input FW tests to prevent bricking the device
#39 & #46 & #34 I need real HW to test && fix these issues

# What ?

All currently supported devices are needed or at least one of them with most of functionality enabled (Checked devices are collected):

- [ ] Huawei B310s-22
- [ ] Huawei B525s-23a
- [ ] Huawei B525s-65a
- [ ] Huawei B715s-23c
- [ ] Huawei E3131
- [ ] Huawei E5186s-22a
... any other device using same admin interface...

# How ?

* You can send me a real HW, contact me via email in my account detail for shipping information (I live in Czech Republic BTW).

* You can donate money to buy these devices (i will try to find some cheap in used condition on auction sites etc. if posible) via donate button on top of this project (PayPal, Patreon). You can specify what device i should buy for that donation.

**All HW/"money for HW" donations will be listed on end of README.md** (Or not if you will not want to be listed)

**Comment by larsvinc** [comment]
Hi! I have a Huawei B535-B232. It seems like most of the API works on it. Is there a way for me to run the full test on the unit I have. All the API commands I have tested, including all SMS commands work, except sending SMS:
>>> client.sms.send_sms(phone_Number,"Test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/huawei_lte_api/api/Sms.py", line 107, in send_sms
    )), dicttoxml_xargs=dicttoxml_xargs)
  File "/usr/local/lib/python3.7/dist-packages/huawei_lte_api/Connection.py", line 22, in wrapped
    return fn(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/huawei_lte_api/Connection.py", line 140, in post
    data = self._check_response_status(self._process_response_xml(response))
  File "/usr/local/lib/python3.7/dist-packages/huawei_lte_api/Connection.py", line 91, in _check_response_status
    error_code
huawei_lte_api.exceptions.ResponseErrorException: 100005: Unknown

**Comment by seipekm** [comment]
B528s-23a not working

**Comment by mynameisv** [comment]
Hi,
your lib works with my Huawei E3531 on a raspberry pi, great job :-) :

:/tmp# lsusb
Bus 001 Device 006: ID 12d1:**** Huawei Technologies Co., Ltd. E161/E169/E620/E800 HSDPA Modem

:/tmp#  gammu identify
Warning: No configuration file found!
Warning: No configuration read, using builtin defaults!
Device               : /dev/ttyUSB0
Manufacturer         : Huawei
Model                : E3531 (E3531)
Firmware             : 22.*************
IMEI                 : 8*************2
SIM IMSI             : 2*************0

:/tmp# python3.7
Python 3.7.6 (default, Dec 19 2019, 09:25:23) 
[GCC 9.2.1 20200104] on linux
>>> from huawei_lte_api.Client import Client
>>> from huawei_lte_api.AuthorizedConnection import AuthorizedConnection
>>> from huawei_lte_api.Connection import Connection
>>> connection = Connection('http://192.168.8.1/')
>>> client = Client(connection)
>>> print(client.device.signal())
{'pci': None, 'sc': '495', 'cell_id': '*****', 'rsrq': None, 'rsrp': None, 'rssi': '-66dBm', 'sinr': None, 'rscp': '-71dBm', 'ecio': '-5dB', 'psatt': '1', 'mode': '2'}

Regards.

**Comment by MulMic** [comment]
Hi Salamek,

I just tried your library on a Huawei "B818-263" aka "4G Router 3 Prime". From your example, run from a RaspberryPi 4 wirh Manjaro (ARCH) Linux. I got:

`{'DeviceName': 'B818-263', 'SerialNumber': 'VNN7S20518002678', 'Imei': '867193043002992', 'Imsi': '262074016901006', 'Iccid': '8949227205105650065', 'Msisdn': '+4917641679119', 'HardwareVersion': 'WL3B818M', 'SoftwareVersion': '10.0.2.2(H190SP1C983)', 'WebUIVersion': 'WEBUI 10.0.2.2(W2SP2C7201)', 'MacAddress1': 'F0:C4:2F:1B:AA:E8', 'MacAddress2': None, 'WanIPAddress': '10.180.170.192', 'wan_dns_address': '62.109.121.17,62.109.121.18', 'WanIPv6Address': None, 'wan_ipv6_dns_address': None, 'ProductFamily': 'LTE', 'Classify': 'cpe', 'supportmode': 'LTE|WCDMA|GSM', 'workmode': 'LTE', 'submask': '255.255.255.255', 'Mccmnc': '26207', 'iniversion': 'B818-263-CUST 8.0.1.1(C965)', 'uptime': '15837', 'ImeiSvn': '01', 'WifiMacAddrWl0': 'F0:C4:2F:1B:AA:E9', 'WifiMacAddrWl1': 'F0:C4:2F:1B:AA:EE', 'spreadname_en': 'HUAWEI 4G Router 3 Prime', 'spreadname_zh': 'HUAWEI 4G Router 3 Prime'}`

Instead of sending you $$$ I can offer to assist you in testing against my hardware, if you like.

MulMic

**Comment by paulzag** [comment]
I've installed on a R-Pi 3+ with Huawei 5576-856 aka Vodafone Pocker Wifi 3 4G. I can send_sms in Australia and I can get_sms from the device. Well done! I gave up on Gammu as it can't talk to the port/device once it becomes an ethernet device.

Do you still need devices? I'd like to help out.

**Comment by Postrediori** [comment]
Hi,

Successfully run data_dump.py on the following models:
* E8372h-608 (USB modem)
* E5573s-320 (LTE router)
* E5530As-2 (3G-only router, just in case)

**Comment by Postrediori** [comment]
Did some testing of K5160 USB stick (Vodafone-branded version of E3372).

**Worked**: net_mode.py script. Tested with operator SIM with specific LTE band: bands and fallback modes are set correctly.
**Didn't work**: A lot of data printed by data_dump.py is empty. Apparently the firmware doesn't fill these fields. E.g. signal data is barely usable with only network mode field:
```
==== Device.signal
{'cell_id': None,
 'ecio': None,
 'lte_bandinfo': None,
 'lte_bandwidth': None,
 'mode': '7',
 'pci': None,
 'psatt': '1',
 'rscp': None,
 'rsrp': None,
 'rsrq': None,
 'rssi': None,
 'sc': None,
 'sinr': None}
```

Version info:
```
==== Device.autorun_version
{'Version': '22.001.07.00.03'}

==== Device.basic_information
{'SoftwareVersion': '10.0',
 'WebUIVersion': '3.019.226',
 'autoupdate_guide_status': '1',
 'classify': 'hilink',
 'devicename': 'K5160',
 'multimode': '0',
 'productfamily': 'LTE',
 'restore_default_status': '0',
 'sim_save_pin_enable': '2'}
```
