### ISSUE TITLE
SMS not working for B535-232

### ISSUE THREAD

**Issue by larsvinc** [Salamek/huawei-lte-api#53]
This api seems to work great for the B535 as well, with the exception of the send_sms function:

>>> client.sms.send_sms(['RETRACTED_NUMBER'],"Test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/huawei_lte_api/api/Sms.py", line 107, in send_sms
    )), dicttoxml_xargs=dicttoxml_xargs)
  File "/usr/local/lib/python3.7/dist-packages/huawei_lte_api/Connection.py", line 22, in wrapped
    return fn(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/huawei_lte_api/Connection.py", line 140, in post
    data = self._check_response_status(self._process_response_xml(response))
  File "/usr/local/lib/python3.7/dist-packages/huawei_lte_api/Connection.py", line 91, in _check_response_status
    error_code
huawei_lte_api.exceptions.ResponseErrorException: 100005: Unknown

Is there a way I can help debugging this to enable sms also for the B535. Ironically most of the other sms API works.

**Comment by larsvinc** [comment]
I debugged this with wireshark, taking a diff of the command sent from the browser and from the python api. The difference was that with the browser, the attribute types was omitted from the command:
<?xml version="1.0" encoding="UTF-8" ?>
<request>
<Index type="int">-1</Index>
<Phones type="list">
<Phone type="str">RETRACTED</Phone>
</Phones>
<Sca type="str"></Sca>
<Content type="str">TESTABCD</Content>
<Length type="int">8</Length>
<Reserved type="int">1</Reserved>
<Date type="str">2019-12-04 18:17:50</Date>
</request>
(sent with library)

<?xml version="1.0" encoding="UTF-8"?>
<request>
<Index>-1</Index>
<Phones>
<Phone>RETRACTED</Phone>
</Phones>
<Sca></Sca>
<Content>Sending AABBWEBT</Content>
<Length>16</Length>
<Reserved>1</Reserved>
<Date>2019-12-04 19:14:47</Date>
</request>
(via web).

I implemented a fix by adding 'attr_type': False to the dicttoxml_xargs in the send_sms, and it worked out fine. The question is if it breaks send_sms for other routers that might require the type declaration. In any case, I will submit a pull request that can be used to close this issue. Then, the library also works for B535-232.
