### ISSUE TITLE
Caused by SSLError(SSLError("bad handshake

### ISSUE THREAD

**Issue by ZyXELis** [Salamek/huawei-lte-api#88]
Hi,

everything was working until an autoupdate of the router, I believe. Now it cannot accept self-signed router SSL certificate.
Is there an option we should use to accept all certificates or ignore it?

B535-232
Current version: 10.0.1.1(H191SP4C983)
--
python3-huawei-lte-api/unknown,now 1.4.14-1 all [installed]

---
send_sms.py:

import sys
from huawei_lte_api.Client import Client
from huawei_lte_api.AuthorizedConnection import AuthorizedConnection
from huawei_lte_api.Connection import Connection

connection = AuthorizedConnection('http://admin:PASSWORD@10.0.0.2/')
client = Client(connection) # This just simplifies access to separate API groups, you can use device = Device(connection) if you want

print(client.sms.send_sms([sys.argv[1]], sys.argv[2]))
------------------

# python3 send_sms.py NUMBER MSG

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 453, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 357, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 459, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.0.0.2', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "send_sms.py", line 7, in <module>
    connection = AuthorizedConnection('http://admin:PASSWORD@10.0.0.2/')
  File "/usr/lib/python3/dist-packages/huawei_lte_api/AuthorizedConnection.py", line 21, in __init__
    super().__init__(clear_url, timeout=timeout)
  File "/usr/lib/python3/dist-packages/huawei_lte_api/Connection.py", line 45, in __init__
    self._initialize_csrf_tokens_and_session()
  File "/usr/lib/python3/dist-packages/huawei_lte_api/Connection.py", line 109, in _initialize_csrf_tokens_and_session
    response = self.session.get(self.url, timeout=self.timeout)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.0.0.2', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

**Comment by Salamek** [comment]
@ZyXELis hi...
well ~correct way how to fix this is make your OS to trust that certificate... somehow... but quick and dirty fix is to modify this line in `/usr/lib/python3/dist-packages/huawei_lte_api/Connection.py` :
https://github.com/Salamek/huawei-lte-api/blob/2b80c180179d056ddaeca86836587953e5f4e0c1/huawei_lte_api/Connection.py#L40

and change it to:
```python
self.session = requests.Session(verify=False) 
```

That disables SSL verification and should get you going... i may expose this parameter to the Connection constructor so you can do it from your code...

**Comment by ZyXELis** [comment]
did not work :(

Traceback (most recent call last):
  File "send_sms.py", line 7, in <module>
    connection = AuthorizedConnection('http://admin:D87tv3RJ52Bzt44n8q@10.0.0.140/')
  File "/usr/lib/python3/dist-packages/huawei_lte_api/AuthorizedConnection.py", line 21, in __init__
    super().__init__(clear_url, timeout=timeout)
  File "/usr/lib/python3/dist-packages/huawei_lte_api/Connection.py", line 40, in __init__
    self.session = requests.Session(verify=False)
TypeError: __init__() got an unexpected keyword argument 'verify'

BUT, I found this:
https://github.com/psf/requests/issues/1034#issuecomment-11477524
which states:

> Session no longer takes arguments in its constructor. Currently the documentation is out of date on this.

So after adding a verify line right after requests line:
`self.session = requests.Session()
self.session.verify = False`

Everything worked again ;) thanks for the pointer. Hope it will be moved to the script itself so it will not vanish after upgrades or container reinstall.

**Comment by wax911** [comment]
Out of curiosity, would it not be somewhat easier/better in the long run (readability and maintenance wise) to allow `sessions` to be a constructor with a default argument for `Connection`? I get that d49445b Added `kwargs` for applying props to session which is also good

**Comment by dartoi** [comment]
Hi, how to restore SSL certificate?
